### PR TITLE
Fixing issues with filtering meshes by ID

### LINKED ISSUE #475: Problem filtering meshresult with object ids
#### Description:

Problem filtering meshresult with object ids. Problem stems from being unable to filter Meshes by Ids. To be added to solve this bug.

#### Steps to reproduce:

Pull any MeshResult and filter by objectids, providing int/string inputs with the sought ids.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #475

 

Fixing issues filtering meshes by Ids. This is done to fix a bug making it now possible to properly filter out MeshResults

 ### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Eo7ARTMF0vpIlM15UzkhF2UBah559sZNdWmLRL6KHFCjGw?e=hLuRmS

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot project compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Review by alelom — APPROVED** [review]
Tested, works. LGTM.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning
@BHoMBot check ready-to-merge

**Pull request merged**
