### PR TITLE
Robot toolkit issue189 reading sections with varying material

### LINKED ISSUE #189: Robot_Toolkit: Section property material does not exist
Reading section properties from Robot fails if the material of the section does not already exist in the in the 
materials dictionary.

in 'ReadMaterial'-method the
`            IRobotCollection rMaterials = labelServer.GetMany(IRobotLabelType.I_LT_MATERIAL);
` seems to not return all materials used in the Robot file.

In the file attached 'ReadMaterial' will only return one Material: 'S355'. However, in 'ReadSectionProperties' secData.MaterialName will return any of 'S355', 'S275' or 'STEEL'.

[missingMaterial_test.zip](https://github.com/BHoM/Robot_Toolkit/files/2889613/missingMaterial_test.zip)

### LINKED ISSUE #205: Robot_Toolkit: Check bars for null releases before create
The Robot adapter crashes on create if the releases are null. Adding a nullcheck and warning for this will help ensuring elements can be pushed.

### LINKED ISSUE #206: Robot_Toolkit: add support for one more box type in read
add support for `IRobotBarSectionShapeType.I_BSST_TRND` for reading box sections

### LINKED ISSUE #207: Robot_Toolkit: Add support for solid circular steel sections for read

### LINKED ISSUE #208: Robot_Toolkit: Add check for concrete type when reading sections
Checking whether the section is actually a concrete type when reading sections

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #189 
Closes #205 
Closes #206 
Closes #207 
Closes #208

 

Mainly fix for #189. Ensuring that all supported sections are read out using their default material. For reading Bars out, the default material is then checked against the material of the bar. If different, a shallow clone will be done, and the material updated to the one of the bars. If a multitude of the same section type, but with different materials, is used, the name of the section will be updated to "SectionLabel - MaterialLabel". Custom data ID of the section will still be the label name.

**NOTE: This might impact running scripts by changing the name of the sections being pulled. If this happends though, it will mean that a critical bug has been fixed for those scripts, as the wrong material might have been associated with the sections!**

Smaller fixes added as well:
- Added support for reading solid circular sections
- Added support for one more box type when reading
- Added check and warning when reading out concrete sections, that not really are concrete
- Null check for releases when creating bars.

 ### Test files

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FRobot_Toolkit%2FRobot_Toolkit-Issue189-ReadMaterialForSectionsIssues

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by alelom** [comment]
Tested it now, getting the following:
image
Full error: 
`1. This component failed to run properly. Are you sure you have the correct type of inputs?
Check their description for more details. Here is the error provided by the method:
Unable to cast COM object of type 'System.__ComObject' to interface type 'RobotOM.IRDimMembDef'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{EC7B6C10-7F98-11D2-990B-00201888053E}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).`

Steps I followed:
1. Build [Issue189 branch](https://github.com/BHoM/Robot_Toolkit/tree/Robot_Toolkit-Issue189-ReadingSectionsWithVaryingMaterial)
2. Build Grasshopper_Toolkit (with Rhino/GH closed)
3. Open GH script. First bool toggle on, opens Robot 2019 on my machine.
4. Open the attached file in Robot.
5. Toggle the second GH Boolean to do the pull.

**Comment by IsakNaslundBh** [comment]
Thaks @alelom . Think this due to another issue (https://github.com/BHoM/Robot_Toolkit/issues/180) that @MartinHenriksen made a quickfix for that he sent over to me (robot was blocked at the time). I could push this as well, but did not want to scope-creep this PR.

@rwemay did you have any particular solution in mind relating to #180, or do you think it is ok to push up what @martin provided me?

**Comment by rwemay** [comment]
Hi guys, yes sorry about the FramingElementDesignProperty code (#180) - was not robust. I didn't get chance to think about a fix I'm afraid, could you share a link to your fix @IsakNaslundBh ?

**Comment by IsakNaslundBh** [comment]
@rwemay I could add a fix for this in this PR as well. Will just be a fix to make it not crash when not working, not fix being able to read everything out.

Only reason for me to not include was to avoid making the PR larger than it already is, but happy to include.

If I do, good if you had a chance to check that it does not break you previous scripts making use of it!

**Comment by rwemay** [comment]
Yes please @IsakNaslundBh ! As Skyped, a simple null check should suffice for now.

**Comment by IsakNaslundBh** [comment]
@rwemay done. Should now still extract what it managed to extract before, only skipping things it did not work for.

I also added a small utility method in the engine, checking for duplicate names and raising warnings if found, then only returning the first one when creating dictionaries. This method should probably be moved to the Engine at some point if agreed useful.

@alelom Do you mind testing again? Also good if more people could test how/if this affects previous scripts made @johannaisak  @njsmithies  @alexradne @rwemay

**Comment by alelom** [comment]
Current behaviour:
image


Warnings:
image

**Comment by IsakNaslundBh** [comment]
Thanks @alelom . Think all of the above is as expected. The intent with this PRs last commits is not not fix the non-working designproperties, but to stop the adapter from crashing, get out the parts that are working and raise warnings for the rest.

**Comment by alexradne** [comment]
I have tried this twice but cant get out anything from the Robot test file. Other robot file worked.  

I have not been able to find out the exact reason why it fails, but it happens when I get to line 90. 
https://github.com/BHoM/Robot_Toolkit/blob/ef270a8caf297a3ba12fac39c3cb67348539af30/Robot_Adapter/Read/Properties/Material.cs#L88-L95
  
image

**Pull request merged**
