### PR TITLE
Fix edge case issues regarding panel geometry

### LINKED ISSUE #467: Edge case panels failing to pull
#### Description:

Some panels failing to be extracted from Robot model due to some edge case geometrical issues, causing an error and crash of the adapter pull:

- Close to linear arc segments. Failing to be generated. Until fixed in Geometry_Engine, should resort to extracting polyline segment and raise warning.
- Openings with empty geometry in Robot failing to pull, crashing the adapter. Check for empty geometry to be implemented and warning raised together with empty opening returned.

#### Steps to reproduce:

Pull from edgecase model

#### Expected behaviour:

For adapter to not crash on pull, and for as much information as possible to be returned, together with appropriate warnings.

### LINKED ISSUE #472: Panel pull is crashing for some invalid geometries
#### Description:

AS title
#### Expected behaviour:

For adapter to pull what it can and not crash,

### LINKED ISSUE #474: MeshResult is extracting Ids in a faulty way
#### Description:

The mesh face and node Ids as not extracted correctly. The fragment rather than the Id in the fragment is used.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #467
Closes #472 
Closes #474 

 

Fixing edge case failures for Panel pull.
Fixing correct ID extracting for pulling of MeshResults

 ### Test files

Model failing in 
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FRobot%5FToolkit%2F%23468%2DFixEdgeCaseIssuesRegardingPanelGeometry&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4

For mesh results fix, try pulling results from FiniteElementCentres using script in:

https://burohappold.sharepoint.com/:f:/s/BHoM/Euqb4hLulcpHt5rN5HDr0j0BAybohnF8ChpsPEUUnipOgQ?e=58eIw4

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Review by alelom — APPROVED** [review]
LGTM!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
