### PR TITLE
Robot toolkit issue247 read load combinations

### LINKED ISSUE #247: Robot_Toolkit: Read load combinations
#### Description:

Load combinations read is not implemented, and the read loadcases also returns combinations which it should not. 

#### Expected behaviour:

Read combinations should return combinations, read cases should return cases.

### PR DESCRIPTION
**Pull request by FredericBourgeon**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #247 

 
This PR fixes the basis of issue #247. It gets the ball rolling but could be improved and build on improvements to loadcase reading.

 ### Additional comments
Some things changed in Robot_Adapter.csproj and read.cs which create a conflict. Should I go for the rebase (here be dragons) or just manually port the new code to a clean branch ?

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
This is great @FredericBourgeon ! 👍 

> Some things changed in Robot_Adapter.csproj and read.cs which create a conflict. Should I go for the rebase (here be dragons) or just manually port the new code to a clean branch ?

Yes, I almost think manually porting the code over to a fresh branch from master would be easier in this case, given how much things that have changed during the Adapter Refactoring process! Hopefully this wont be a to painful process given the code does not affect to many files. 

Thanks!

**Comment by alelom** [comment]
Hi @FredericBourgeon, thanks a lot for your contribution!
I agree with @IsakNaslundBh, in this case porting the code to a fresh branch from master would definitely be the simplest solution. We changed quite a few things during the refactoring.
Feel free to ping me for any question!
Cheers!

**Comment by FredericBourgeon** [comment]
Cheers @alelom & @IsakNaslundBh, will do! I'll drop test files as well with the new PR.

**Comment by IsakNaslundBh** [comment]
> Cheers @alelom & @IsakNaslundBh, will do! I'll drop test files as well with the new PR.

Brilliant. Cheers!

**Comment by IsakNaslundBh** [comment]
Closing in favour of https://github.com/BHoM/Robot_Toolkit/pull/313

**Pull request closed without merging**
