### PR TITLE
Fixes #185

### LINKED ISSUE #185: Robot_Toolkit: Add support for geometrical line loads

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #185 

 

- Adding GeometricalLineLoad objects
- Adding create method for the new load
- Adding push capabilities

 ### Test files

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Robot_Toolkit/Robot_Toolkit-Issue185-GeometricLineLoads/Robot_Toolkit-Issue185-GeometricLineLoads.gh?csf=1&e=3E2mvb

 ### Changelog

#### Added:
- Adding support for geometric line loads for panels

### CODE REVIEW

**Comment by alexradne** [comment]
What is the reason for having the GeometricalLineLoad object being in the Robot namespace? `BH.oM.Adapters.Robot`

**Comment by JosefTaylor** [comment]
@alexradne the various <software>_toolkit Engines can be used as sandboxes for things that will eventually make it into the BHoM engine. There are already plans to use this for other FEA packages, so this will probably get promoted before too long.

**Comment by IsakNaslundBh** [comment]
@ Yes, as Josef said. Implementing it here where it was needed before promoting it to a full BHoM class. Same as with the contour loads added about a week ago.

**Comment by IsakNaslundBh** [comment]
thanks @alexradne

**Pull request merged**
