### PR TITLE
Robot toolkit: Add support for tapered sections

### LINKED ISSUE #477: Add support for tapered sections
#### Description:

Need support for pushing and pulling of tapered sections that are supported by Robot. To begin with this entails sections that consists of two section cuts, one for start and one for end, assuming linear interpolation and with the same shape type at start and end.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #477 

 

 ### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EpgVkfEZy_hNlPfsVgicUJ8BvBNoLwyeZPFg7nvmAasZ8g?e=Dl3BL7

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot fix copyright headers ref. 4842799234

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by TosteSkDa — COMMENTED** [review]
Ran through the test script and pushed to robot. Double checked that all values match what is defined in Grasshopper. Everything works except for Angle(L) profile and RectangularToBox profile. Also seems to be a bug with tapered fabricatedBoxProfile where none of the sizes are displayed in the Sections tab (see image), but the object with the profile still seems to be created correctly with all the right values. Also checked with my own project script and all tapered sections gets pushed correctly.
TaperedFabricatedBoxProfileRobotBug

**Comment by IsakNaslundBh** [comment]
@TosteSkDa have pushed a fix for the box sections now, if you can have another look! :)

**Review by TosteSkDa — APPROVED** [review]
Everything works now. Nice fix on the FabricatedBox issue. Missed the warning messages given for box to rectangle and angle sections before, but seen that they show up now. Good job!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
