### PR TITLE
Make use of caching system in base adapter

### LINKED ISSUE #503: Make use of Caching system
#### Description:

Tweak all read methods in RObot to make use of the caching system added in https://github.com/BHoM/BHoM_Adapter/pull/337

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Adapter/pull/337
intentionally using different branch names to let the Adapter PR be merged separately.

 ### Issues addressed by this PR

 Closes #503

 

Make use of the Caching system added to the Base adapter. Aim for this to speed up the push process, especially for higher level objects.

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Review by alelom — APPROVED** [review]
Code changes look good. I used the create-read test script and it works well.

**Comment by alelom** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by alelom** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
