### PR TITLE
Robot_Toolkit: Fix case and combination pull

### LINKED ISSUE #491: Robot_Toolkit: Loadcase and Combination error
#### Description:
First issue: Pulling load case, the load combinations also get pull which isn't ideal.

Second issue: The load case skip numbers and as a result when the combinations are pulled it used the loadcase index instead of the number resulting in a combination being used in a combination.

#### Test file(s):

[Robot load combination pull error.zip](https://github.com/BHoM/Robot_Toolkit/files/8737961/Robot.load.combination.pull.error.zip)

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #491 

 

Fixes errors when pulling cases and combinations

 ### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Robot_Toolkit/%23492-FixCaseAndCombinationPull?csf=1&web=1&e=faICcf

 ### Changelog

- Support for pulling combinations of combinations added.

 ### Additional comments

### CODE REVIEW

**Review by johannaisak — APPROVED** [review]
Works as expected and just saved me a lot of faff on a project, thanks Isak/Joe!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
