### PR TITLE
Robot_Adapter: Fix crash on pulling panels with hosted Beams or Columns

### LINKED ISSUE #451: Robot_Toolkit: Convert.FromRobot(RobotNode) crashing when pulling in panel
#### Description:

image

When pulling panels from the model linked below (a Robot tutorial model) this error occurs and the pull crashes with no output. By using Selection Requests I have isolated the problem to the topmost floor panel - every other panel pulls in fine.

#### Steps to reproduce:

Pull in all panels or, using selection requests, only the topmost floor panel from the model linked below.

#### Expected behaviour:

All panels being pulled in without crashes, but possibly descriptive errors if applicable.

#### Test file(s):

[Structure-Seismic.zip](https://github.com/BHoM/Robot_Toolkit/files/5850756/Structure-Seismic.zip)

### PR DESCRIPTION
**Pull request by IsakLarbornBH**
### Issues addressed by this PR

 Closes #451 

 
Currently, the Robot Adapter assumes that every hosted object of a panel is an Opening. This is not always the case, Panels in Robot can host other objects, such as beams. This PR fixes the crash associated with pulling panels which host beams or columns.

 ### Test files

See linked issue for a Robot file that can not be pulled in without this fix.

 ### Additional comments

Note that the check added by this PR only filters out hosted objects with the Structural Type of Beam or Column. The remaining types are Slab, Wall and Undefined. 

I have tested this on multiple Robot files, some pushed from the BHoM, some created in Robot. This PR does not break any of them, and none of them have openings of any type other than Undefined.

Whether Slab and Wall should also be filtered out is an issue left for later - as is whether Undefined objects could be something other than openings. Whether there are other potential crashes related to assumptions regarding hosted objects has not been investigated.

### CODE REVIEW

**Comment by IsakLarbornBH** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
