### PR TITLE
Fix project compliance

### LINKED ISSUE #521: 6.2 project compliance
As noted: https://github.com/BHoM/Robot_Toolkit/pull/519/checks?check_run_id=14441665185

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #521

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 14745191733

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Review by peterjamesnugent — APPROVED** [review]
Checked by inspection - compliance fixes (confirmed by compliance check).

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
