### PR TITLE
Robot toolkit issue213 align with changes in b ho m

### LINKED ISSUE #175: Robot_Toolkit: Spelling errors and name updates for loads in BHoM
Aligning with changes made in https://github.com/BHoM/BHoM/issues/382

### LINKED ISSUE #213: Robot_Toolkit: Update due to changes in Structures_oM
Update due to changes made in:

https://github.com/BHoM/BHoM/issues/464
https://github.com/BHoM/BHoM_Engine/issues/922

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/481
https://github.com/BHoM/BHoM_Engine/pull/951

 ### Issues addressed by this PR

 Closes #213 
Closes #175 

 

Aligning with changes made in BHoM and Engine
MeshFace methods removed to align with the updated oM

 ### Test files

Please test through as much of existing projects/scripts as possible to ensure the Robot-link is still functioning as before

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by alexradne** [comment]
I get an error on line 50. `type.BaseType` is null for the type `MaterialFragment` when pushing bars with the new serialised materials. 
https://github.com/BHoM/Robot_Toolkit/blob/317685107f25e8370e73f8079480dc7ccaa54aee/Robot_Adapter/Types/DependencyTypes.cs#L42-L50

**Comment by IsakNaslundBh** [comment]
Thanks @alexradne ! Really good catch! Need a null check protection there.

@rwemay think this is the cause of the problem we just discussed over skype!

**Comment by alexradne** [comment]
New error unfortunately:

`1. Solution exception:The best overloaded method match for 'BH.Engine.Robot.Convert.DataBaseStringFormat(BH.oM.Structure.SectionProperties.ISectionProperty)' has some invalid arguments`

```C#
public static string IDataBaseStringFormat(IBHoMObject obj)
        {
            return DataBaseStringFormat(obj as dynamic);
        }
```

**Comment by IsakNaslundBh** [comment]
Fix pushed again, not able to test, as have quite massive etabs script open right now.

Again, thanks @alexradne , and sorry!

**Comment by rwemay** [comment]
Thanks both, push panel working for me too now.

**Comment by jdarcyBHE** [comment]
Pushing to Robot seems to be working as before, no issues experienced.

**Pull request merged**
