### PR TITLE
Migrated ContourLoad and GeometricalLineLoad to BHoM

### LINKED ISSUE #246: Robot_Toolkit: Update toolkit to target loads migrated to main oM and engine
#### Parent issue(s) or Pull Request(s) causing the changes:

https://github.com/BHoM/BHoM/issues/534
https://github.com/BHoM/BHoM_Engine/issues/1128

#### Description:

Load classes currently residing in the Robot_Toolkit are to be migrated to the main BHoM.

Adapter/engine should be updated to target these new objects.

### PR DESCRIPTION
**Pull request by JosefTaylor**
### NOTE: Depends on 
https://github.com/BHoM/BHoM/pull/580

 ### Issues addressed by this PR

 Closes #246 

 
Migrated GeometricalLineLoad and ContourLoad to BHoM Structure_oM

 ### Test files

https://burohappold.sharepoint.com/:u:/s/BHoM/EXmzAXtdndZNi7NoAa_9s5MBUSz4FBICHKM9fgpjWrsR7g?e=EA9YGh

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by JosefTaylor** [comment]
Not sure why the CI checks failed- my branch is named the same as the BHoM branch it depends on. @FraserGreenroyd?

**Comment by FraserGreenroyd** [comment]
@JosefTaylor the reason for the failure is currently set to:
image

Did the references to the new loads within BHoM get updated when you removed the ones from here?

**Comment by JosefTaylor** [comment]
> Did the references to the new loads within BHoM get updated when you removed the ones from here?

it built on my machine immediately after building BHoM with the migrated methods, since Robot already referenced the structure_oM.

**Comment by FraserGreenroyd** [comment]
Problem found to be in the dependent PR needing the `csproj` file updated, checks now passing successfully :smile:

**Comment by IsakNaslundBh** [comment]
@JosefTaylor Think rather than removing the old files here, we should be using the same strategy as for the Levels change. This is Deprecating the old ones, making some sort of Upgrade() method and making sure both of them works. 

This is to avoids scripts breaking making use of the older load classes.

**Comment by JosefTaylor** [comment]
@IsakNaslundBh Will do

**Comment by JosefTaylor** [comment]
@IsakNaslundBh Ready to go!

**Comment by JosefTaylor** [comment]
I'm sitting on changes to BHoM_Engine to get the engine.create methods up, but want to wait till a few PRs are merged before pushing them off my local machine.

**Pull request merged**
