### PR TITLE
Fix beta-documentation-compliance failures

### LINKED ISSUE #541: Fix beta-documentation-compliance failures
#### Broken rules:

https://github.com/BHoM/Robot_Toolkit/pull/540/checks?check_run_id=22829206589

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

 Closes #541 

 

 ### Test files

check documentation-compliance

 ### Changelog

- Changed `GetStringFromENum" to extension methods

 ### Additional comments

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check documentation-compliance

**Review by FraserGreenroyd — APPROVED** [review]
All compliant now, thanks @peterjamesnugent

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
