### PR TITLE
Add support for pulling new Modal results from robot

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1521

 ### Issues addressed by this PR

 

Add support for pulling of new modal results classes from Robot.

 ### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Structure_oM/%231521-AddUpdatedStructuralDynamicsResults?csf=1&web=1&e=OeKgWS

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by zm247 — APPROVED** [review]

**Review by zm247 — APPROVED** [review]

**Comment by zm247** [comment]
Isak,  PR's approved for the dynamic model extraction. Thanks for sorting this out. Hopefully we will get it on the next Beta version.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
@zm247's review is sufficient but is not picked up by the bot due to being an extra comment so this approval is for merging purposes only. No review has been undertaken except that by @zm247

**Pull request merged**
